// Do not edit. This file is generated by the Makefile of the repository.
package man

const Section1 = `CITOP(1)                                                                                                                                                                          CITOP(1)

NAME
       citop – Continuous Integration Table Of Pipelines

SYNOPSIS
       citop

DESCRIPTION
       citop shows the CI pipelines associated to a git commit

INTERACTIVE COMMANDS
       Key         Action
       ───────────────────────────────────────────────────────────
       Up, j       Move cursor up by one line
       Down, k     Move cursor down by one line
       Page Up     Move cursor up by one screen
       Page Down   Move cursor down by one screen
       o, +        Open the fold at the cursor
       O           Open the fold at the cursor and all sub-folds
       c, -        Close the fold at the cursor
       C           Close the fold at the cursor and all sub-folds
       /           Open search prompt
       Escape      Close search prompt
       Enter, n    Move to the next match
       N           Move to the previous match
       v           View the log of the job at the cursor[a]
       b           Open with default web browser
       q           Quit
       ?           View manual page

       • [a] Note that if the job is still running the log may be incomplete.

CONFIGURATION FILE
   Location
       citop  follows  the XDG base directory specification [1] and expects to find the configuration file at one of the following locations depending of the value of the two environment
       variables XDG_CONFIG_HOME and XDG_CONFIG_DIRS:

       1. "$XDG_CONFIG_HOME/citop/citop.toml"

       2. "$DIR/citop/citop.toml" for every directory DIR in the comma-separated list "$XDG_CONFIG_DIRS"

       If XDG_CONFIG_HOME is not set, citop uses the default value "$HOME/.config" instead.  If XDG_CONFIG_DIRS is not set, citop uses the default value "/etc/xdg" instead.

   Format
       citop uses a configuration file in TOML version v0.5.0 format.

       Full example:

              # The 'providers' array is mostly used to define credential for accessing online services. citop
              # relies on two types of providers:
              #    - 'source providers' are used for listing the CI pipelines associated to a given commit
              #   (GitHub and GitLab are source providers).
              #    - 'CI providers' are used to get detailed information about CI pipelines (GitLab, AppVeyor,
              #    CircleCI, Travis are CI providers)
              #
              # citop requires credentials for at least one source provider and one CI provider to run.
              #
              [providers]

              [[providers.gitlab]]
              # Name of the provider to be shown in the TUI (optional, default: "gitlab")
              name = "gitlab.com"
              # URL of the gitlab instance (optional, default: "https://gitlab.com")
              url = "https://gitlab.com"
              # Personal access token for accessing the GitLab API
              # Tokens can be generated at https://gitlab.com/profile/personal_access_tokens
              token = "gitlab_api_token"

              [[providers.github]]
              # Personal access token for accessing the GitHub API
              # Tokens can be generated at https://github.com/settings/tokens
              token = "github_api_token"

              [[providers.travis]]
              # Name of the provider to be shown in the TUI (optional, default: "travis")
              name = "travis.org"
              # URL of the travis instance ("org" and "com" can be used as shorthands for the URL
              # of travis.org and travis.com)
              url = "org"
              # Personal access token for accessing the Travis API
              # Token generation procedure: https://developer.travis-ci.org/authentication
              token = "travis_org_api_token"

              # Another travis instance with a different name, URL and access token
              [[providers.travis]]
              name = "travis.com"
              url = "com"
              token = "travis_com_api_token"

              [[providers.appveyor]]
              # Name of the provider to be shown in the TUI (optional, default: "appveyor")
              name = "appveyor"
              # API key for accessing the AppVeyor API
              # Keys can be generated here: https://ci.appveyor.com/api-keys
              token = "appveyor_api_key"

              [[providers.circleci]]
              # Name of the provider to be shown in the TUI (optional, default: "circleci")
              name = "circleci"
              # Personal API token to access the CircleCI API
              # Tokens can be managed here: https://circleci.com/account/api
              token = "circleci_api_token"

ENVIRONMENT VARIABLES
       • BROWSER is used to find the path of the default web browser

       • HOME, XDG_CONFIG_HOME and XDG_CONFIG_DIRS are used to locate the configuration file

EXAMPLES
       Check pipeline status after pushing a commit:

              $ git add .
              $ git commit -m 'Commit message'
              $ git push
              $ citop

NOTES
       1. https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

AUTHORS
       Nicolas Bedos.

                                                                                       November 2019                                                                              CITOP(1)`
