.PHONY: usage clean image tests releases citop
.SILENT:

export GO111MODULE=on
# Enable static linking
export CGO_ENABLED=0

# Directory used to store the result of the build process
BUILD=build
# Name of the executable
EXEC=citop
# Name of the go project
PACKAGE=citop
PACKAGE_PATH=github.com/nbedos/citop
VERSION=$(shell git describe --tags --dirty)


usage:
	echo "Usage:"
	echo "    make citop       # Build executable and manual pages (requires pandoc)"
	echo "    make clean       # Remove build directory"
	echo "    make image       # Build Docker image"
	echo "    make man.go      # Build manual page in go format (requires pandoc)"
	echo "    make releases    # Build release archives"
	echo "    make tests       # Run unit tests"

citop: man.go $(BUILD) $(BUILD)/LICENSE $(BUILD)/$(EXEC).man.html $(BUILD)/$(EXEC).man.1
	BUILD_VERSION="$(VERSION)_$$(go env GOOS)/$$(go env GOARCH)" && \
	echo "Building $(BUILD)/$(EXEC)... (version $$BUILD_VERSION)" && \
	go build -ldflags "-X main.Version=$$BUILD_VERSION" -o "$(BUILD)/$(EXEC)"

$(BUILD)/$(EXEC).man.html : man.md $(BUILD) pandoc_template.html
	echo "Building $@..." && \
	sed '1s/\\<version\\>/$(VERSION)/' man.md | \
	pandoc -s -t html5 --template pandoc_template.html > $@

$(BUILD)/$(EXEC).man.1 : man.md $(BUILD)
	echo "Building $@..." && \
	sed '1s/\\<version\\>/$(VERSION)/' man.md | \
	pandoc -s -t man >  $@

releases: man.go $(BUILD) $(BUILD)/LICENSE $(BUILD)/$(EXEC).man.1 $(BUILD)/$(EXEC).man.html
	echo "Starting release..." && \
	go version && \
	pandoc -v | head -n1 && \
	for GOARCH in amd64; \
	do \
	    for GOOS in linux freebsd openbsd netbsd osx; \
	    do \
		DIR="$(PACKAGE)-$(VERSION)-$$GOOS-$$GOARCH" && \
		ARCHIVE="$(BUILD)/$$DIR.tar.gz" && \
		echo "Building $$ARCHIVE..." && \
		mkdir -p "$(BUILD)/$$DIR" && \
		go build -ldflags "-X \"main.Version=$(VERSION) $$GOOS/$$GOARCH\"" -o "$(BUILD)/$(EXEC)" && \
		cp "$(BUILD)/$(EXEC)" "$(BUILD)/LICENSE" "$(BUILD)/$(EXEC).man.html" "$(BUILD)/$(EXEC).man.1" "$(BUILD)/$$DIR/" && \
		tar -C "$(BUILD)" -czf "$$ARCHIVE" "$$DIR" ; \
	    done ; \
	done && \
	cd "$(BUILD)" && sha1sum *gz

$(BUILD):
	mkdir -p $(BUILD)

clean:
	rm -rf $(BUILD)

man.go : man.md
	# Generate a go file containing the manual page for embedding in the executable
	echo "Building $@..."
	{ \
	    echo "// Do not edit. This file is generated by running 'make generated'." ; \
	    echo "package main" ; \
	    echo ; \
	    echo "import \"strings\"" ; \
	    echo ; \
	    echo "const generated = \`$$(pandoc -s -t man $< | sed 's/`/` + "`" + `/g')\`" ; \
	    echo ; \
	    echo "func manualPage() string {" ; \
	    echo "	return strings.Replace(generated, \"<version>\", Version, 1)" ; \
	    echo "}" ; \
	    echo "" ; \
	} > man.go

$(BUILD)/LICENSE : go.mod go.sum $(BUILD)
	# Concatenate license of $(PACKAGE) and licenses of dependencies
	echo "Building $@..." ;
	{ \
	    echo -e "Below is the license of $(PACKAGE) and of every package it uses" ; \
	    echo -e "\n\n====== $(PACKAGE_PATH) ======\n" ; \
	    fold -s LICENSE ; \
	    for pkg_dir in $$(go list -f '{{.Dir}}' -m all | grep -v $(PACKAGE)); \
	    do \
		find "$$pkg_dir" \
		    -maxdepth 1 \
		    -name LICENSE \
		    -exec echo -e "\n\n====== $$(echo $$pkg_dir | sed 's/.*\/go\/pkg\/mod\/\(.*\)/\1/') ======\n" \; \
		    -exec fold -s {} \; ; \
	    done \
	} > $@

tests:
	go test -v ./...

image:
	docker build -t "$(EXEC):$(VERSION)" .
