.PHONY: usage build generated license tests
.DEFAULT: usage

export GO111MODULE=on
export CGO_ENABLED=0

BUILD=build
EXECUTABLE=citop
LICENSES_THIRD_PARTY=LICENSES_THIRD_PARTY
PACKAGE=citop
VERSION=$(shell git describe --tags --long --dirty)


usage:
	@echo "Usage:"
	@echo "    make build       # Build executable and manual pages (requires pandoc)"
	@echo "    make generated   # Build machine-generated source code (requires pandoc)"
	@echo "    make license     # Build third-party license"
	@echo "    make tests       # Run unit tests"

build: generated
	@mkdir -p "$(BUILD)"
	@MD="$$(sed '1s/<version>/$(VERSION)/' man.md)" && \
	echo "Building $(BUILD)/man.html..." && \
	echo "$$MD" | pandoc -s -t html5 --css './style.css' > $(BUILD)/man.html && \
	echo "Building $(BUILD)/$(EXECUTABLE).man.1..." && \
	echo "$$MD" | pandoc -s -t man >  $(BUILD)/$(EXECUTABLE).man.1
	@echo "Building $(BUILD)/$(EXECUTABLE)... (version $(VERSION))"
	@go build -ldflags "-X main.Version=$(VERSION)" -o "$(BUILD)/$(EXECUTABLE)"

generated: man.md
	@echo "Building man.go..."
	@{ \
	    echo "// Do not edit. This file is generated by running 'make generated'." ; \
	    echo "package main" ; \
	    echo ; \
	    echo "import \"strings\"" ; \
	    echo ; \
	    echo "const generated = \`$$(pandoc -s -t man $< | sed 's/`/` + "`" + `/g')\`" ; \
	    echo ; \
	    echo "func manualPage() string {" ; \
	    echo "	return strings.Replace(generated, \"<version>\", Version, 1)" ; \
	    echo "}" ; \
	    echo "" ; \
	} > man.go

license:
	@echo "Building $(LICENSES_THIRD_PARTY)..."
	@{ \
	    echo -e "Below is a copy of the license of every package used by $(PACKAGE)" ; \
	    for pkg_dir in $$(go list -f '{{.Dir}}' -m all | grep -v $(PACKAGE)); \
	    do \
		find "$$pkg_dir" \
		    -maxdepth 1 \
		    -name LICENSE \
		    -exec echo -e "\n\n====== $$(echo $$pkg_dir | sed 's/.*\/\(go\/.*\)/\1/') ======\n" \; \
		    -exec fold -s {} \; ; \
	    done \
	} > $(LICENSES_THIRD_PARTY)

tests:
	go test -v ./...

