// Do not edit. This file was generated by the build script.
package main

const manualPage = `.\"t
.\" Automatically generated by Pandoc 2.8
.\"
.TH "CISTERN" "1" "" "" ""
.hy
.SH NAME
.PP
\f[B]cistern\f[R] \[en] Continuous Integration Table Of Pipelines
.SH SYNOPSIS
.PP
\f[C]cistern [-r REPOSITORY | --repository REPOSITORY] [COMMIT]\f[R]
.PP
\f[C]cistern -h | --help\f[R]
.PP
\f[C]cistern --version\f[R]
.SH DESCRIPTION
.PP
cistern monitors the CI pipelines associated to a specific commit of a
git repository.
.PP
cistern currently integrates with the following online services.
Each of the service is one or both of the following:
.IP \[bu] 2
A \[lq]source provider\[rq] that is used to list the pipelines
associated to a given commit of an online repository
.IP \[bu] 2
A \[lq]CI provider\[rq] that is used to get detailed information about
CI builds
.PP
.TS
tab(@);
lw(14.6n) lw(8.8n) lw(7.8n) lw(27.2n).
T{
Service
T}@T{
Source
T}@T{
CI
T}@T{
URL
T}
_
T{
GitHub
T}@T{
yes
T}@T{
no
T}@T{
<https://github.com/>
T}
T{
GitLab
T}@T{
yes
T}@T{
yes
T}@T{
<https://gitlab.com/>
T}
T{
AppVeyor
T}@T{
no
T}@T{
yes
T}@T{
<https://www.appveyor.com/>
T}
T{
CircleCI
T}@T{
no
T}@T{
yes
T}@T{
<https://circleci.com/>
T}
T{
Travis CI
T}@T{
no
T}@T{
yes
T}@T{
<https://travis-ci.org/> <https://travis-ci.com/>
T}
T{
Azure Devops
T}@T{
no
T}@T{
yes
T}@T{
<https://dev.azure.com>
T}
.TE
.SH POSITIONAL ARGUMENTS
.SS \f[C]COMMIT\f[R]
.PP
Specify the commit to monitor.
COMMIT is expected to be the SHA identifier of a commit, or the name of
a tag or a branch.
If this option is missing cistern will monitor the commit referenced by
HEAD.
.PP
Example:
.IP
.nf
\f[C]
# Show pipelines for commit 64be3c6
cistern 64be3c6
# Show pipelines for the commit referenced by the tag \[aq]0.9.0\[aq]
cistern 0.9.0
# Show pipelines for the commit at the tip of a branch
cistern feature/doc
\f[R]
.fi
.SH OPTIONS
.SS \f[C]-r=REPOSITORY, --repository=REPOSITORY\f[R]
.PP
Specify the git repository to monitor.
If REPOSITORY is the path of a local repository, cistern will monitor
all the associated remotes.
If REPOSITORY is a URL, cistern will monitor the corresponding online
repository.
.PP
If this option is not set, cistern will behave as if it had been set to
the path of the current directory.
.PP
Note that cistern will only monitor repositories hosted on GitLab or
GitHub.
.PP
Examples:
.IP
.nf
\f[C]
# Monitor pipelines of the git repository in the current directory
cistern
# Monitor pipelines of the repository specified by a web URL
cistern -r https://gitlab.com/nbedos/cistern
cistern -r github.com/nbedos/cistern
# Git URLs are accepted
cistern -r git\[at]github.com:nbedos/cistern.git
# A path referring to a local repository is valid too
cistern -r /home/user/repos/myrepo
\f[R]
.fi
.SS \f[C]-h, --help\f[R]
.PP
Show usage of cistern
.SS \f[C]--version\f[R]
.PP
Print the version of cistern being run
.SH COLUMNS
.SS REF
.PP
Tag or branch associated to the pipeline
.SS PIPELINE
.PP
Identifier of the pipeline
.SS TYPE
.PP
Either \[lq]P\[rq] (Pipeline), \[lq]S\[rq] (Stage), \[lq]J\[rq] (Job) or
\[lq]T\[rq] (Task)
.SS STATE
.PP
State of the pipeline
.SS XFAIL
.PP
Expected failure.
Boolean indicating whether this step is allowed to fail without
impacting the overall state of the pipeline
.SS CREATED, STARTED, FINISHED
.PP
Date when the pipeline was created, started or finished
.SS DURATION
.PP
Time it took for the pipeline to finish
.SS NAME
.PP
Name of the provider followed by the name of the pipeline, if any
.SS URL
.PP
URL of the step on the website of the provider
.SH INTERACTIVE COMMANDS
.PP
Below are the default commands for interacting with cistern.
.PP
.TS
tab(@);
lw(10.7n) lw(46.7n).
T{
Key
T}@T{
Action
T}
_
T{
Up, j
T}@T{
Move cursor up by one line
T}
T{
Down, k
T}@T{
Move cursor down by one line
T}
T{
Right, l
T}@T{
Scroll right
T}
T{
Left, h
T}@T{
Scroll left
T}
T{
Page Up
T}@T{
Move cursor up by one screen
T}
T{
Page Down
T}@T{
Move cursor down by one screen
T}
T{
<
T}@T{
Move sort column left
T}
T{
>
T}@T{
Move sort column right
T}
T{
!
T}@T{
Reverse sort order
T}
T{
o, +
T}@T{
Open the fold at the cursor
T}
T{
O
T}@T{
Open the fold at the cursor and all sub-folds
T}
T{
c, -
T}@T{
Close the fold at the cursor
T}
T{
C
T}@T{
Close the fold at the cursor and all sub-folds
T}
T{
/
T}@T{
Open search prompt
T}
T{
Escape
T}@T{
Close search prompt
T}
T{
Enter, n
T}@T{
Move to the next match
T}
T{
N
T}@T{
Move to the previous match
T}
T{
v
T}@T{
View the log of the job at the cursor[a]
T}
T{
b
T}@T{
Open with default web browser
T}
T{
q
T}@T{
Quit
T}
T{
?
T}@T{
View manual page
T}
.TE
.IP \[bu] 2
[a] Note that if the job is still running, the log may be incomplete.
.SH CONFIGURATION FILE
.SS Location
.PP
cistern follows the XDG base directory specification [2] and expects to
find the configuration file at one of the following locations depending
on the value of the two environment variables \f[C]XDG_CONFIG_HOME\f[R]
and \f[C]XDG_CONFIG_DIRS\f[R]:
.IP "1." 3
\f[C]\[dq]$XDG_CONFIG_HOME/cistern/cistern.toml\[dq]\f[R]
.IP "2." 3
\f[C]\[dq]$DIR/cistern/cistern.toml\[dq]\f[R] for every directory
\f[C]DIR\f[R] in the comma-separated list
\f[C]\[dq]$XDG_CONFIG_DIRS\[dq]\f[R]
.PP
If \f[C]XDG_CONFIG_HOME\f[R] (resp.
\f[C]XDG_CONFIG_DIRS\f[R]) is not set, cistern uses the default value
\f[C]\[dq]$HOME/.config\[dq]\f[R] (resp.
\f[C]\[dq]/etc/xdg\[dq]\f[R]) instead.
.SS Format
.PP
cistern uses a configuration file in TOML version
v0.5.0 (https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.5.0.md)
format.
.PP
The complete format of the configuration file is described in the
example included in the release archives which is also available on
GitHub (https://github.com/nbedos/cistern/blob/master/cmd/cistern/cistern.toml)
.SS Minimal example
.PP
This is a minimal example of a configuration file focused mostly on
setting up credentials.
It should be enough to get you started running cistern.
.IP
.nf
\f[C]
#### CISTERN CONFIGURATION FILE ####
# This is a configuration file for cistern that should be located at
# $XDG_CONFIG_HOME/cistern/cistern.toml

## GENERIC OPTIONS ##
# List of columns displayed on screen. Available columns are 
# \[dq]ref\[dq], \[dq]pipeline\[dq], \[dq]type\[dq], \[dq]state\[dq], \[dq]created\[dq], \[dq]started\[dq],
# \[dq]finished\[dq], \[dq]duration\[dq], \[dq]xfail\[dq], \[dq]name\[dq], \[dq]url\[dq]
columns = [\[dq]ref\[dq], \[dq]pipeline\[dq], \[dq]type\[dq], \[dq]state\[dq], \[dq]started\[dq], \[dq]duration\[dq], \[dq]name\[dq], \[dq]url\[dq]]

# Name of the column used for sorting the table prefixed by an
# optional \[dq]+\[dq] (ascending order) or \[dq]-\[dq] (descending order).
sort = \[dq]-started\[dq]


## PROVIDERS ##
[providers]
# The sections below define credentials for accessing source 
# providers (GitHub, GitLab) and CI providers (GitLab, Travis,
# AppVeyor, Azure Devops, CircleCI).
#
# Feel free to remove any section as long as you leave one
# section for a source provider and one for a CI provider.
# 
# When an API token is not set or set to the empty string,
# cistern will still run but with some limitations:
#     - GitHub: cistern will hit the rate-limit for
#     unauthenticated requests in a few minutes
#     - GitLab: cistern will NOT be able to access pipeline
#     jobs
#

### GITHUB ###
[[providers.github]]
# GitHub API token (optional, string)
# GitHub token management: https://github.com/settings/tokens
token = \[dq]\[dq]


### GITLAB ###
[[providers.gitlab]]
# GitLab instance URL (optional, string, default:
# \[dq]https://gitlab.com\[dq])
# (the GitLab instance must support GitLab REST API V4)
url = \[dq]https://gitlab.com\[dq]

# GitLab API token (optional, string)
# gitlab.com token management:
#     https://gitlab.com/profile/personal_access_tokens
token = \[dq]\[dq]


### TRAVIS CI ###
[[providers.travis]]
# URL of the Travis instance. \[dq]org\[dq] and \[dq]com\[dq] can be used as
# shorthands for the full URL of travis.org and travis.com
# (string, mandatory)
url = \[dq]org\[dq]

# API access token for the travis API (string, optional).
# Travis tokens are managed at:
#    - https://travis-ci.org/account/preferences
#    - https://travis-ci.com/account/preferences
token = \[dq]\[dq]


# Define another account for accessing travis.com
[[providers.travis]]
url = \[dq]com\[dq]
token = \[dq]\[dq]


### APPVEYOR ###
[[providers.appveyor]]
# AppVeyor API token (optional, string)
# AppVeyor token managemement: https://ci.appveyor.com/api-keys
token = \[dq]\[dq]


### CIRCLECI ###
[[providers.circleci]]
# Circle CI API token (optional, string)
# See https://circleci.com/account/api
token = \[dq]\[dq]


### AZURE DEVOPS ###
[[providers.azure]]
# Azure API token (optional, string)
# Azure token management is done at https://dev.azure.com/ via
# the user settings menu
token = \[dq]\[dq]
\f[R]
.fi
.SH ENVIRONMENT
.SS ENVIRONMENT VARIABLES
.IP \[bu] 2
\f[C]BROWSER\f[R] is used to find the path of the default web browser
.IP \[bu] 2
\f[C]PAGER\f[R] is used to view log files.
If the variable is not set, cistern will call \f[C]less\f[R]
.IP \[bu] 2
\f[C]HOME\f[R], \f[C]XDG_CONFIG_HOME\f[R] and \f[C]XDG_CONFIG_DIRS\f[R]
are used to locate the configuration file
.SS LOCAL PROGRAMS
.PP
cistern relies on the following local executables:
.IP \[bu] 2
\f[C]less\f[R] to view log files, unless \f[C]PAGER\f[R] is set
.IP \[bu] 2
\f[C]man\f[R] to show the manual page
.IP \[bu] 2
\f[C]git\f[R] (optional) to translate the abbreviated SHA identifier of
a commit into a non-abbreviated SHA and also to support "` + "`" + `"insteadOf' and
"` + "`" + `"pushInsteadOf' configuration options for remote URLs
.SH EXAMPLES
.PP
Monitor pipelines of the current git repository
.IP
.nf
\f[C]
# Move to a directory containing a git repository of your choosing
git clone git\[at]github.com:nbedos/cistern.git && cd cistern
# Run cistern to list the pipelines associated to the last commit of the repository 
cistern

# Show pipelines associated to a specific commit, tag or branch
cistern a24840c
cistern 0.1.0
cistern master
\f[R]
.fi
.PP
Monitor pipelines of other repositories
.IP
.nf
\f[C]
# Show pipelines of a repository identified by a URL or path
cistern -r https://gitlab.com/nbedos/cistern        # Web URL
cistern -r git\[at]github.com:nbedos/cistern.git        # Git URL
cistern -r github.com/nbedos/cistern                # URL without scheme
cistern -r /home/user/repos/repo                    # Path to a repository

# Specify both repository and git reference
cistern -r github.com/nbedos/cistern master
\f[R]
.fi
.SH BUGS
.PP
Questions, bug reports and feature requests are welcome and should be
submitted on GitHub (https://github.com/nbedos/cistern/issues).
.SH NOTES
.IP "1." 3
\f[B]cistern repository\f[R]
.RS 4
.IP \[bu] 2
<https://github.com/nbedos/cistern>
.RE
.IP "2." 3
\f[B]XDG base directory specification\f[R]
.RS 4
.IP \[bu] 2
<https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html>
.RE
.SH AUTHORS
Nicolas Bedos.
`
