// Do not edit. This file was generated by the build script.
package main

const manualPage = `.\"t
.\" Automatically generated by Pandoc 1.19.2.4
.\"
.TH "CISTERN" "1" "" "" ""
.hy
.SH NAME
.PP
\f[B]cistern\f[] \[en] Continuous Integration Table Of Pipelines
.SH SYNOPSIS
.PP
\f[C]cistern\ [\-r\ REPOSITORY\ |\ \-\-repository\ REPOSITORY]\ [COMMIT]\f[]
.PP
\f[C]cistern\ \-h\ |\ \-\-help\f[]
.PP
\f[C]cistern\ \-\-version\f[]
.SH DESCRIPTION
.PP
cistern monitors the CI pipelines associated to a specific commit of a
git repository.
.PP
cistern currently integrates with the following online services.
Each of the service is one or both of the following:
.IP \[bu] 2
A "source provider" that is used to list the pipelines associated to a
given commit of an online repository
.IP \[bu] 2
A "CI provider" that is used to get detailed information about CI builds
.PP
.TS
tab(@);
lw(14.6n) lw(8.8n) lw(7.8n) lw(26.2n).
T{
Service
T}@T{
Source
T}@T{
CI
T}@T{
URL
T}
_
T{
GitHub
T}@T{
yes
T}@T{
no
T}@T{
<https://github.com/>
T}
T{
GitLab
T}@T{
yes
T}@T{
yes
T}@T{
<https://gitlab.com/>
T}
T{
AppVeyor
T}@T{
no
T}@T{
yes
T}@T{
<https://www.appveyor.com/>
T}
T{
CircleCI
T}@T{
no
T}@T{
yes
T}@T{
<https://circleci.com/>
T}
T{
Travis CI
T}@T{
no
T}@T{
yes
T}@T{
<https://travis-ci.org/> <https://travis-ci.com/>
T}
T{
Azure Devops
T}@T{
no
T}@T{
yes
T}@T{
<https://dev.azure.com>
T}
.TE
.SH POSITIONAL ARGUMENTS
.SS \f[C]COMMIT\f[]
.PP
Specify the commit to monitor.
COMMIT is expected to be the SHA identifier of a commit, or the name of
a tag or a branch.
If this option is missing cistern will monitor the commit referenced by
HEAD.
.PP
Example:
.IP
.nf
\f[C]
#\ Show\ pipelines\ for\ commit\ 64be3c6
cistern\ 64be3c6
#\ Show\ pipelines\ for\ the\ commit\ referenced\ by\ the\ tag\ \[aq]0.9.0\[aq]
cistern\ 0.9.0
#\ Show\ pipelines\ for\ the\ commit\ at\ the\ tip\ of\ a\ branch
cistern\ feature/doc
\f[]
.fi
.SH OPTIONS
.SS \f[C]\-r=REPOSITORY,\ \-\-repository=REPOSITORY\f[]
.PP
Specify the git repository to monitor.
If REPOSITORY is the path of a local repository, cistern will monitor
all the associated remotes.
If REPOSITORY is a URL, cistern will monitor the corresponding online
repository.
.PP
If this option is not set, cistern will behave as if it had been set to
the path of the current directory.
.PP
Note that cistern will only monitor repositories hosted on GitLab or
GitHub.
.PP
Examples:
.IP
.nf
\f[C]
#\ Monitor\ pipelines\ of\ the\ git\ repository\ in\ the\ current\ directory
cistern
#\ Monitor\ pipelines\ of\ the\ repository\ specified\ by\ a\ web\ URL
cistern\ \-r\ https://gitlab.com/nbedos/cistern
cistern\ \-r\ github.com/nbedos/cistern
#\ Git\ URLs\ are\ accepted
cistern\ \-r\ git\@github.com:nbedos/cistern.git
#\ A\ path\ referring\ to\ a\ local\ repository\ is\ valid\ too
cistern\ \-r\ /home/user/repos/myrepo
\f[]
.fi
.SS \f[C]\-h,\ \-\-help\f[]
.PP
Show usage of cistern
.SS \f[C]\-\-version\f[]
.PP
Print the version of cistern being run
.SH INTERACTIVE COMMANDS
.PP
Below are the default commands for interacting with cistern.
.PP
.TS
tab(@);
lw(10.7n) lw(45.7n).
T{
Key
T}@T{
Action
T}
_
T{
Up, j
T}@T{
Move cursor up by one line
T}
T{
Down, k
T}@T{
Move cursor down by one line
T}
T{
Page Up
T}@T{
Move cursor up by one screen
T}
T{
Page Down
T}@T{
Move cursor down by one screen
T}
T{
o, +
T}@T{
Open the fold at the cursor
T}
T{
O
T}@T{
Open the fold at the cursor and all sub\-folds
T}
T{
c, \-
T}@T{
Close the fold at the cursor
T}
T{
C
T}@T{
Close the fold at the cursor and all sub\-folds
T}
T{
/
T}@T{
Open search prompt
T}
T{
Escape
T}@T{
Close search prompt
T}
T{
Enter, n
T}@T{
Move to the next match
T}
T{
N
T}@T{
Move to the previous match
T}
T{
v
T}@T{
View the log of the job at the cursor[a]
T}
T{
b
T}@T{
Open with default web browser
T}
T{
q
T}@T{
Quit
T}
T{
?
T}@T{
View manual page
T}
.TE
.IP \[bu] 2
[a] Note that if the job is still running, the log may be incomplete.
.SH CONFIGURATION FILE
.SS Location
.PP
cistern follows the XDG base directory specification [2] and expects to
find the configuration file at one of the following locations depending
on the value of the two environment variables \f[C]XDG_CONFIG_HOME\f[]
and \f[C]XDG_CONFIG_DIRS\f[]:
.IP "1." 3
\f[C]"$XDG_CONFIG_HOME/cistern/cistern.toml"\f[]
.IP "2." 3
\f[C]"$DIR/cistern/cistern.toml"\f[] for every directory \f[C]DIR\f[] in
the comma\-separated list \f[C]"$XDG_CONFIG_DIRS"\f[]
.PP
If \f[C]XDG_CONFIG_HOME\f[] (resp.
\f[C]XDG_CONFIG_DIRS\f[]) is not set, cistern uses the default value
\f[C]"$HOME/.config"\f[] (resp.
\f[C]"/etc/xdg"\f[]) instead.
.SS Format
.PP
cistern uses a configuration file in TOML version
v0.5.0 (https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.5.0.md)
format.
The configuration file is made of keys grouped together in tables.
The specification of each table is given in the example below.
.SS Example
.PP
This example describes and uses all existing configuration options.
.IP
.nf
\f[C]
####\ CISTERN\ CONFIGURATION\ FILE\ ####
#\ This\ file\ is\ a\ complete,\ valid\ configuration\ file\ for\ cistern
#\ and\ should\ be\ located\ at\ $XDG_CONFIG_HOME/cistern/cistern.toml
#\ 

##\ PROVIDERS\ ##
[providers]
#\ The\ \[aq]providers\[aq]\ table\ is\ used\ to\ define\ credentials\ for\ 
#\ accessing\ online\ services.\ cistern\ relies\ on\ two\ types\ of
#\ providers:
#
#\ \ \ \ \-\ \[aq]source\ providers\[aq]\ are\ used\ for\ listing\ the\ CI\ pipelines
#\ \ \ \ associated\ to\ a\ given\ commit\ (GitHub\ and\ GitLab\ are\ source
#\ \ \ \ providers)
#\ \ \ \ \-\ \[aq]CI\ providers\[aq]\ are\ used\ to\ get\ detailed\ information\ about
#\ \ \ \ CI\ pipelines\ (GitLab,\ AppVeyor,\ CircleCI,\ Travis\ and\ Azure
#\ \ \ \ Devops\ are\ CI\ providers)
#
#\ cistern\ requires\ credentials\ for\ at\ least\ one\ source\ provider\ and
#\ one\ CI\ provider\ to\ run.\ Feel\ free\ to\ remove\ sections\ below\ 
#\ as\ long\ as\ this\ rule\ is\ met.
#
#\ Note\ that\ for\ all\ providers,\ not\ setting\ an\ API\ token\ or\ 
#\ setting\ "` + "`" + `"token\ =\ """` + "`" + `"\ will\ cause\ the\ provider\ to\ make
#\ unauthenticated\ API\ requests.\ 
#

###\ GITHUB\ ###
[[providers.github]]
#\ GitHub\ API\ token\ (optional,\ string)
#
#\ Note:\ Unauthenticated\ API\ requests\ are\ heavily\ rate\-limited\ by\ 
#\ GitHub\ (60\ requests\ per\ hour\ and\ per\ IP\ address)\ whereas\ 
#\ authenticated\ clients\ benefit\ from\ a\ rate\ of\ 5000\ requests\ per
#\ hour.\ Providing\ an\ \ API\ token\ is\ strongly\ encouraged:\ without
#\ one,\ cistern\ will\ likely\ reach\ the\ rate\ limit\ in\ a\ matter\ of
#\ minutes.
#
#\ GitHub\ token\ management:\ https://github.com/settings/tokens
token\ =\ ""


###\ GITLAB\ ###
[[providers.gitlab]]
#\ Name\ shown\ by\ cistern\ for\ this\ provider
#\ (optional,\ string,\ default:\ "gitlab")
name\ =\ "gitlab"

#\ GitLab\ instance\ URL\ (optional,\ string,\ default:\ "https://gitlab.com")
#\ (the\ GitLab\ instance\ must\ support\ GitLab\ REST\ API\ V4)
url\ =\ "https://gitlab.com"

#\ GitLab\ API\ token\ (optional,\ string)
#
#\ Note:\ GitLab\ prevents\ access\ to\ pipeline\ jobs\ for\ 
#\ unauthenticated\ users\ meaning\ if\ you\ wish\ to\ use\ cistern
#\ to\ view\ GitLab\ pipelines\ you\ will\ have\ to\ provide
#\ appropriate\ credentials.\ This\ is\ true\ even\ for\ pipelines
#\ of\ public\ repositories.
#
#\ gitlab.com\ token\ management:
#\ \ \ \ \ https://gitlab.com/profile/personal_access_tokens
token\ =\ ""


###\ TRAVIS\ CI\ ###
[[providers.travis]]
#\ Name\ shown\ by\ cistern\ for\ this\ provider
#\ (optional,\ string,\ default:\ "travis")
name\ =\ "travis"

#\ URL\ of\ the\ Travis\ instance.\ "org"\ and\ "com"\ can\ be\ used\ as
#\ shorthands\ for\ the\ full\ URL\ of\ travis.org\ and\ travis.com
#\ (string,\ mandatory)
url\ =\ "org"

#\ API\ access\ token\ for\ the\ travis\ API\ (string,\ optional)
#\ Travis\ tokens\ are\ managed\ at:
#\ \ \ \ \-\ https://travis\-ci.org/account/preferences
#\ \ \ \ \-\ https://travis\-ci.com/account/preferences
token\ =\ ""


#\ Define\ another\ account\ for\ accessing\ travis.com
[[providers.travis]]
name\ =\ "travis"
url\ =\ "com"
token\ =\ ""


###\ APPVEYOR\ ###
[[providers.appveyor]]
#\ Name\ shown\ by\ cistern\ for\ this\ provider
#\ (optional,\ string,\ default:\ "appveyor")
name\ =\ "appveyor"

#\ AppVeyor\ API\ token\ (optional,\ string)
#\ AppVeyor\ token\ managemement:\ https://ci.appveyor.com/api\-keys
token\ =\ ""


###\ CIRCLECI\ ###
[[providers.circleci]]
#\ Name\ shown\ by\ cistern\ for\ this\ provider
#\ (optional,\ string,\ default:\ "circleci")
name\ =\ "circleci"

#\ Circle\ CI\ API\ token\ (optional,\ string)
#\ See\ https://circleci.com/account/api
token\ =\ ""


###\ AZURE\ DEVOPS\ ###
[[providers.azure]]
#\ Name\ shown\ by\ cistern\ for\ this\ provider
#\ (optional,\ string,\ default:\ "azure")
name\ =\ "azure"

#\ Azure\ API\ token\ (optional,\ string)
#\ Azure\ token\ management\ is\ done\ at\ https://dev.azure.com/\ via
#\ the\ user\ settings\ menu
token\ =\ ""
\f[]
.fi
.SH ENVIRONMENT
.SS ENVIRONMENT VARIABLES
.IP \[bu] 2
\f[C]BROWSER\f[] is used to find the path of the default web browser
.IP \[bu] 2
\f[C]PAGER\f[] is used to view log files.
If the variable is not set, cistern will call \f[C]less\f[]
.IP \[bu] 2
\f[C]HOME\f[], \f[C]XDG_CONFIG_HOME\f[] and \f[C]XDG_CONFIG_DIRS\f[] are
used to locate the configuration file
.SS LOCAL PROGRAMS
.PP
cistern relies on the following local executables:
.IP \[bu] 2
\f[C]less\f[] to view log files, unless \f[C]PAGER\f[] is set
.IP \[bu] 2
\f[C]man\f[] to show the manual page
.IP \[bu] 2
\f[C]git\f[] (optional) to translate the abbreviated SHA identifier of a
commit into a non\-abbreviated SHA and also to support
\[aq]insteadOf\[aq] and \[aq]pushInsteadOf\[aq] configuration options
for remote URLs
.SH EXAMPLES
.PP
Monitor pipelines of the current git repository
.IP
.nf
\f[C]
#\ Move\ to\ a\ directory\ containing\ a\ git\ repository\ of\ your\ choosing
git\ clone\ git\@github.com:nbedos/cistern.git\ &&\ cd\ cistern
#\ Run\ cistern\ to\ list\ the\ pipelines\ associated\ to\ the\ last\ commit\ of\ the\ repository\ 
cistern

#\ Show\ pipelines\ associated\ to\ a\ specific\ commit,\ tag\ or\ branch
cistern\ a24840c
cistern\ 0.1.0
cistern\ master
\f[]
.fi
.PP
Monitor pipelines of other repositories
.IP
.nf
\f[C]
#\ Show\ pipelines\ of\ a\ repository\ identified\ by\ a\ URL\ or\ path
cistern\ \-r\ https://gitlab.com/nbedos/cistern\ \ \ \ \ \ \ \ #\ Web\ URL
cistern\ \-r\ git\@github.com:nbedos/cistern.git\ \ \ \ \ \ \ \ #\ Git\ URL
cistern\ \-r\ github.com/nbedos/cistern\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ #\ URL\ without\ scheme
cistern\ \-r\ /home/user/repos/repo\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ #\ Path\ to\ a\ repository

#\ Specify\ both\ repository\ and\ git\ reference
cistern\ \-r\ github.com/nbedos/cistern\ master
\f[]
.fi
.SH BUGS
.PP
Questions, bug reports and feature requests are welcome and should be
submitted on GitHub (https://github.com/nbedos/cistern/issues).
.SH NOTES
.IP "1." 3
\f[B]cistern repository\f[]
.RS 4
.IP \[bu] 2
<https://github.com/nbedos/cistern>
.RE
.IP "2." 3
\f[B]XDG base directory specification\f[]
.RS 4
.IP \[bu] 2
<https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html>
.RE
.SH AUTHORS
Nicolas Bedos.
`
